vim.o.textwidth = 100
vim.o.expandtab = false -- Convert tabs to spaces
vim.o.tabstop = 2 -- Tab size in spaces
vim.o.shiftwidth = 2 -- Spaces inserted for a tab
vim.o.wrap = true
vim.cmd('set iskeyword+=- shortmess+=ca formatoptions-=cro formatoptions+=n')
vim.o.incsearch = true
TERMINAL = vim.fn.expand('$TERMINAL')
vim.cmd('let &titleold="' .. TERMINAL .. '"')
vim.o.title = true
vim.o.titlestring = "%{expand('%:t')} - NVim"
vim.o.fileencoding = "utf-8" -- The encoding written to file
vim.o.encoding = 'utf-8'
vim.o.mouse = "a" -- Enable mouse
vim.o.clipboard = "unnamedplus" -- Enable clipboard
vim.o.termguicolors = true -- use gui, not cterm
vim.o.showtabline = 2 -- Always show buffers
vim.o.hidden = true -- Keep multiple buffers in memory
vim.o.showmode = false
vim.cmd('set whichwrap+=<,>,[,],h,l') -- move to next line with thes
vim.o.cmdheight = 1 -- More space for displaying messages
vim.o.pumheight = 10 -- Makes popup menu smaller
vim.o.undofile = true
vim.o.backup = false
vim.o.writebackup = false
vim.o.swapfile = false
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.colorcolumn = "0" -- fix indentline for now
vim.o.cursorline = true
vim.o.cursorcolumn = true
vim.o.number = true -- set numbered lines
vim.o.relativenumber = false -- relative to current line
vim.o.smarttab = true
vim.o.linebreak = true
vim.o.breakindent = true
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.foldmethod = 'indent'
vim.o.foldnestmax = 1
vim.o.foldcolumn = '0' -- width of fold tree column
vim.o.foldlevel = 100
vim.o.foldenable = false
vim.o.updatetime = 300 -- Faster completion
vim.o.timeoutlen = 500 -- By default timeoutlen is 1000 ms
vim.o.signcolumn = "yes" -- Always show the signcolumn
-- vim.o.conceallevel = 0
DATA_PATH = vim.fn.stdpath('data')
CACHE_PATH = vim.fn.stdpath('cache')
require'nvim_comment'.setup()
