-- for sumneko_lua to work, you need to have a .git dir in parent
-- directory of your current file, otherwise it will keep recursively
-- searching for the .git directory -> keep the empty .git dir here
require('plugins')
require('utils')
require('settings')
require('keymappings')
require('coloring')
require('autocommands')
require('ranger')
require('startify')
require('statusline')
require('barbar')
require('hexokinase')
require('treesitter')
require('autocompletion')
require('telescope-finder')
require('autopairs')
require('nvimtree')
require('lsp-installer')

-- LSP
require('lsp')
require('lsp.bash-ls')
require('lsp.clangd')
require('lsp.css-ls')
-- require('lsp.dart-ls')
-- require('lsp.docker-ls')
require('lsp.efm-general-ls')
require('lsp.emmet-ls')
-- require('lsp.go-ls')
-- require('lsp.graphql-ls')
require('lsp.html-ls')
require('lsp.js-ts-ls')
require('lsp.json-ls')
-- require('lsp.kotlin-ls')
require('lsp.latex-ls')
require('lsp.lua-ls')
-- require('lsp.php-ls')
require('lsp.python-ls')
-- require('lsp.ruby-ls')
require('lsp.rust-ls')
-- require('lsp.svelte-ls')
require('lsp.tailwindcss-ls')
-- require('lsp.terraform-ls')
require('lsp.vim-ls')
require('lsp.yaml-ls')
