#!/usr/bin/env bash
# Backlight detection
if [ "$button" -a "$button" != 2 ]; then
	[ $button -eq 1 -o $button -eq 4 ] &&
		xbacklight + 10 || xbacklight - 10
fi

LIGHT=$(xbacklight)
LIGHT=${LIGHT%.*}
TEXT="<b> $LIGHT%</b>"
printf "%s\n%s\n" "$TEXT" "$TEXT"
~/.config/i3blocks/colorcode $LIGHT
