#!/bin/bash
# Copyright (C) 2020 Josef Litoš

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
if [[ $button -eq 1 ]]; then
	xbacklight = $(rofi -dmenu -location 3 -l 0 -p " [0-100]")
	sleep 0.15
fi

TEXT=$(xbacklight | awk '{ printf("%.f", $1) }')
echo "<b> $TEXT%</b>"
echo " $TEXT%"
~/.config/i3blocks/colorcode $TEXT
