#!/bin/bash
# Copyright (C) 2020 Josef Litoš

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#FontAwesome icons for use
#       ⚡ 
TEXT=$(acpi | cut -d " " -f3-5 | sed "s/,//g;s/Discharging//;s/Charging//;s/Unknown//;s/Full//;s/:..$//;s/ 0/ /g")

if ! [ "$TEXT" ]; then
	TEXT=
else
	STATE=$(echo "$TEXT" | sed "s/^. //;s/\%.*//")
	if [[ $STATE -le 20 ]]; then
		TEXT=$(echo $TEXT | sed "s///")
	elif [[ $STATE -le 40 ]]; then
		TEXT=$(echo $TEXT | sed "s///")
	elif [[ $STATE -le 60 ]]; then
		TEXT=$(echo $TEXT | sed "s///")
	elif [[ $STATE -le 80 ]]; then
		TEXT=$(echo $TEXT | sed "s///")
	fi
	if [[ $STATE -gt 15 ]] && ! [[ $TEXT == *""* ]] && ! [[ $button -eq 1 ]]; then
		TEXT=$(echo $TEXT | sed "s/ ..%//")
	elif [[ $STATE -le 6 ]] && [[ $TEXT == *""* ]]; then
		case "$(echo -en "I'll plug it in\nSuspend\nPower off" | rofi -dmenu -l 3 -p " $STATE%")" in
			"Suspend") systemctl suspend;;
			"Power off") systemctl poweroff;;
		esac
	fi
fi

echo $TEXT
echo $TEXT
~/.config/i3blocks/colorcode $STATE
