#!/usr/bin/env bash
#Battery status script
#FontAwesome icons for use
#       ⚡ 
line=($(acpi))
TEXT=${line[2]:0:1}
STATE=${line[3]%\%*}
TIME=${line[4]%:??}
#TEXT=$(acpi | cut -d " " -f3-5 | sed "s/,//g;s/Discharging//;s/Charging//;s/Unknown//;s/Full//;s/:..$//;s/ 0/ /g")

if [ -z "$TEXT" -o "$TEXT" = 'rate' ]; then
	TEXT=
else
	case "$TEXT" in
		'D')
			[ $STATE -le 20 ] && TEXT= ||
			[ $STATE -le 40 ] && TEXT= ||
			[ $STATE -le 60 ] && TEXT= ||
			[ $STATE -le 80 ] && TEXT= || TEXT=
			if [ $STATE -le 6 ]; then
				case "$(rofi -dmenu -l 3 -p " $STATE%" <<< "I'll plug it in
Suspend
Power off")" in
					"Suspend") systemctl suspend;;
					"Power off") systemctl poweroff;;
				esac
			fi;;
		'C') TEXT=;;
		'F') TEXT=;;
		*) TEXT=;;
	esac
	TEXT="$TEXT $STATE% $TIME"
fi

printf "%s\n%s\n" "$TEXT" "$TEXT"
~/.config/i3blocks/colorcode $STATE
