#!/bin/bash
#Battery status detection
#FontAwesome icons for use
#       ⚡ 
TEXT=$(acpi | cut -d " " -f3-5 | sed "s/,//g;s/Discharging//;s/Charging//;s/Unknown//;s/Full//;s/:..$//;s/ 0/ /g")

if ! [ "$TEXT" ]; then
	TEXT=
else
	STATE=$(echo "$TEXT" | sed "s/^. //;s/\%.*//")
	if [[ $STATE -le 20 ]]; then
		TEXT=$(echo $TEXT | sed "s///")
	elif [[ $STATE -le 40 ]]; then
		TEXT=$(echo $TEXT | sed "s///")
	elif [[ $STATE -le 60 ]]; then
		TEXT=$(echo $TEXT | sed "s///")
	elif [[ $STATE -le 80 ]]; then
		TEXT=$(echo $TEXT | sed "s///")
	fi
	if [[ $STATE -gt 15 ]] && ! [[ $TEXT == *""* ]] && ! [[ $button -eq 1 ]]; then
		TEXT=$(echo $TEXT | sed "s/ ..%//")
	elif [[ $STATE -le 6 ]] && [[ $TEXT != *""* ]]; then
		case "$(echo -en "I'll plug it in\nSuspend\nPower off" | rofi -dmenu -l 3 -p " $STATE%")" in
			"Suspend") systemctl suspend;;
			"Power off") systemctl poweroff;;
		esac
	fi
fi

echo $TEXT
echo $TEXT
~/.config/i3blocks/colorcode $STATE
