#!/usr/bin/env bash
# Clock script
if [ "$button" = 1 ]; then
	date +" %H:%M:%S"
	date +" %H:%M:%S"
else
	date +" %H:%M"
	date +" %H:%M"
fi
~/.config/i3blocks/colorcode $(bc <<< "($(date +%H)*3600+$(date +%M))/432")

[ $(date +"%H") -ge 21 ] && xrandr --output LVDS1 --gamma 1:0.85:0.75 || exit 0

