#!/bin/bash
#Clock script
if [[ $button -eq 1 ]]; then
	date +" %H:%M:%S"
	date +" %H:%M:%S"
else
	date +" %H:%M"
	date +" %H:%M"
fi
~/.config/i3blocks/colorcode $[($(date +%H | sed "s/^0//")*3600+$(date +%M | sed "s/^0//"))/432]

if [[ $(date +"%H") -ge 20 ]]; then
	xrandr --output LVDS1 --gamma 1:0.9:0.8 >> /dev/null
fi

