#!/bin/bash
#Author: Josef Litoš
#Echos a color between red and green (0 for red, 100 for green)

#OPACITY=$(printf '%x\n' 200)

fix() {
	echo "$([[ $1 -le 16 ]] && echo 0)$(printf '%x\n' $1)"
}

#input in format: color [0-255] [0-255] [0-255]
color() {
	echo "#$(fix $1)$(fix $2)$(fix $3)"
}

if [[ $1 -ge 200 ]]; then
	x=0
elif [[ $1 -gt 100 ]]; then
	x=$((200-$1))
elif [ $1 ]; then
	x=$1
else
	echo "#881eaa"
	exit
fi

#x ranged to [0-190]

# normal 0=red 100=green
redtogreen() {
	if [[ $x -le 50 ]]; then
		let x=$x*380/100+30
		color 220 $x 30
	else
		let x=(100-$x)*380/100+30
		color $x 220 30
	fi
}

#rainbow mod 0=red 40=green 80=blue 100=violet
rainbow() {
	if [[ $x -le 20 ]]; then
		let x=$x*95/10+30
		color 220 $x 30
	elif [[ $x -le 40 ]]; then
		let x=(40-$x)*95/10+30
		color $x 220 30
	elif [[ $x -le 60 ]]; then
		let x=($x-40)*95/10+30
		color 30 220 $x
	elif [[ $x -le 80 ]]; then
		let x=(80-$x)*95/10+30
		color 30 $x 220
	else
		let x=($x-80)*95/10+30
		color $x 30 220
	fi
}

redtogreen

