#!/usr/bin/env bash
# CPU temperature script

declare -i c=0 t=0
while read -a line; do
	[ "${line[0]}" = 'Core' ] && t+=${line[2]:1:2} && c+=1
done <<< $(sensors -A)
declare -i temp=t/c

if [ $temp -le 45 ]; then
	TEXT=" <b>$temp°C</b>"
elif [ $temp -le 60 ]; then
	TEXT=" <b>$temp°C</b>"
elif [ $temp -le 75 ]; then
	TEXT=" <b>$temp°C</b>"
elif [ $temp -le 90 ]; then
	TEXT=" <b>$temp°C</b>"
else
	TEXT=" <b>$temp°C</b>"
fi

printf '%s\n%s\n' "$TEXT" "$TEXT"
# temp-30 because lowest temp is practically 30° C
~/.config/i3blocks/colorcode $[100-(temp-30)/7*10]
