#!/usr/bin/env bash
# Fan speed script

while read -a LINE; do
	[ "${LINE[0]}" = 'fan1:' ] && SPEED=${LINE[1]} && break
done <<< $(sensors)

if [ $SPEED ]; then
	speed_round=$(bc <<< "scale=1;$SPEED/1000")
	TEXT=" <b>"$speed_round"k</b>"
else
   TEXT=""
fi
echo $TEXT
echo $TEXT
~/.config/i3blocks/colorcode $[100-SPEED/45]
