#!/usr/bin/env bash
# CPU temperature

while read -a LINE; do
	[ "${LINE[0]}" = 'temp1:' ] && TEMP=${LINE[1]:1:2} && break
done <<< $(sensors)

if [ $TEMP -le 45 ]; then
	TEXT=" <b>$TEMP°C</b>"
elif [ $TEMP -le 60 ]; then
	TEXT=" <b>$TEMP°C</b>"
elif [ $TEMP -le 75 ]; then
	TEXT=" <b>$TEMP°C</b>"
elif [ $TEMP -le 90 ]; then
	TEXT=" <b>$TEMP°C</b>"
else
	TEXT=" <b>$TEMP°C</b>"
fi

printf '%s\n%s\n' "$TEXT" "$TEXT"
# TEMP-30 because lowest temp is practically 30° C
~/.config/i3blocks/colorcode $[100-(TEMP-30)/7*10]
