#!/bin/bash
#Basic guide for my i3 setup usage

SELECTED=$(echo \
"Super/WinKey   Rofi app launcher
Mod+R          Rofi command launcher
Mod+E          PcManFM
Mod+1          Firefox
Mod+2          NeoVim
Mod+Alt+2      Geany
Mod+Enter/3    st
Mod+(Shift)+V  Volume adj
Mod+(Shift)+B  Backlight adj" | rofi -dmenu -location 3 -p "select action" | sed -e "s/^...............//")

start() {
	case "$SELECTED" in
		"Rofi app launcher") i3 exec "rofi -show drun -location 3";;
		"Rofi command launcher") i3 exec "rofi -show run -location 3";;
		"PcManFM") i3 exec pcmanfm;;
		"Firefox") i3 exec firefox;;
		"NeoVim") i3 exec st -e nvim;;
		"Mousepad") i3 exec mousepad;;
		"st") i3 exec st;;
		"Volume adj") ./signal vol $(rofi -dmenu -location 3 -l 0 -p " ±[0-200]") >> /dev/null;;

		"Backlight adj") ./signal light = $(rofi -dmenu -location 3 -l 0 -p " [0-100]");;
	esac
}
start >> /dev/null

