#!/bin/sh
#Basic guide for my i3 setup usage

SELECTED=$(echo \
"Mod+R          Rofi app launcher
Mod+E          PcManFM
Mod+1          Firefox
Mod+2          NeoVim
Mod+Alt+2      Notepadqq
Mod+Enter/3    st
Mod+(Shift)+V  Volume adj
Mod+(Shift)+B  Backlight adj
Mod+Q          Close window
Mod+Esc/X      Session options" | rofi -dmenu -location 3 -l 10 -p "select action" | sed -e "s/^...............//")

start() {
	case "$SELECTED" in
		"Rofi app launcher") rofi -show drun -location 3 &;;
		"PcManFM") pcmanfm &;;
		"Firefox") firefox &;;
		"NeoVim") st -e nvim &;;
		"Notepadqq") notepadqq &;;
		"st") st &;;
		"Volume adj") sleep 1 && ./signal vol $(rofi -dmenu -location 3 -l 0 -p " ±[0-200]") >> /dev/null;;
		"Backlight adj") sleep 1 && ./signal light = $(rofi -dmenu -location 3 -l 0 -p " [0-100]");;
		"Close window") xkill -id $(xdotool getactivewindow);;
		"Session options") xdotool key super+x;
	esac
}
start >> /dev/null

disown
