#!/bin/bash

SELECTED=$(echo \
"Mod+R          Rofi app launcher
Mod+E          PcManFM
Mod+1          Firefox
Mod+2          NeoVim
Mod+Alt+2      Mousepad
Mod+Enter/3    st
Mod+(Shift)+M  Volume adj
Mod+(Shift)+B  Backlight adj" | rofi -dmenu -location 3 -p "help menu" | sed -e "s/^...............//")

start() {
	case "$SELECTED" in
		"Rofi app launcher") i3 exec rofi -drun;;
		"PcManFM") i3 exec pcmanfm;;
		"Firefox") i3 exec firefox;;
		"NeoVim") i3 exec st -e nvim;;
		"Mousepad") i3 exec mousepad;;
		"st") i3 exec st;;
		"Volume adj") pactl set-sink-volume @DEFAULT_SINK@ $(rofi -dmenu -location 3 -l 0 -p " ±[0-200]")% >> /dev/null;;
		"Backlight adj") xbacklight = $(rofi -dmenu -location 3 -l 0 -p " [0-100]"); pkill -RTMIN+11 i3blocks;;
	esac
}
start >> /dev/null

