#!/bin/sh
#Memory usage, total mem usage on click

declare -i MTotal MUsed STotal SUsed
while read -a line; do
	case ${line[0]} in
		"Mem:") MTotal=${line[1]}; MUsed=${line[2]}+${line[4]};;
		"Swap") STotal=${line[1]}; SUsed=${line[2]};;
	esac
done <<< $(free -m)

if [ "$BLOCK_INSTANCE" == "swap" ]; then
	USED=$SUsed
	TOTAL=$(bc <<< "scale=1;$STotal/1024")
	PCT=$(bc <<< "scale=1;$SUsed/$STotal*100")
else
	USED=$MUsed
	TOTAL=$(bc <<< "scale=1;$MTotal/1024")
	PCT=$(bc <<< "scale=1;$MUsed*100/$MTotal")
fi

if [ $USED -ge 1000 ]; then
	TYPE="G"; USED=$(bc <<< "scale=1;$USED/1024")
else
	TYPE="M"
fi

# Nice icons:  
if [[ $button -eq 1 ]]; then
	TEXT=" $USED$TYPE/${TOTAL}G ($PCT%)"
elif [[ $button -eq 3 ]]; then
	ps axo rss,comm \
                | awk '{ proc_list[$2]++; proc_list[$2 "," 1] += $1; } \
                END { for (proc in proc_list) { printf("%d\t%s\n", \
                proc_list[proc "," 1],proc); }}' | sort -n | tail -n 10 | sort -rn \
                | awk '{$1/=1024;printf "%.0fMB\t",$1}{print $2}' \
					 | rofi -dmenu -location 3 -p ramuse >> /dev/null
	TEXT="<b> $PCT%</b>"
else
	TEXT="<b> $PCT%</b>"
fi
echo $TEXT
echo $TEXT
~/.config/i3blocks/colorcode $[100-${PCT/.*/}]
