#!/bin/bash
#Signal managing script for statusbar

case "$1" in
	"vol")
		pactl set-sink-volume @DEFAULT_SINK@ $2%
		pkill -RTMIN+10 i3blocks;;
	"mute")
		pactl set-sink-mute @DEFAULT_SINK@ $2
		pkill -RTMIN+10 i3blocks;;
	"light")
		xbacklight $2 $3
		sleep 0.2
		pkill -RTMIN+11 i3blocks;;
esac
