#!/usr/bin/env bash
# Checks for system updates, requires pacman-contrib installed

if [ "$button" = 1 ]; then
	while read LINE; do
		[[ "$LINE" = 'set $term'* ]] && \
			i3 exec "${LINE##* } -e paru" &>/dev/null && break
	done < ~/.config/i3/config
	COUNT=0
else
	[[ "$(uptime)" = *" 0 min, "* ]] && sleep 10
	declare -i COUNT=0
	while read LINE; do
		[ "$LINE" ] && COUNT+=1 && \
			[[ "$LINE" = "linux"* ]] && URGENT=1
	done <<< $(checkupdates)
fi

TEXT=" <b>$COUNT</b>"
printf '%s\n%s\n' "$TEXT" "$TEXT"
~/.config/i3blocks/colorcode $[100+COUNT]
[ "$URGENT" ] && exit 33 || exit 0

