#!/usr/bin/env bash
# Checks for system updates, requires pacman-contrib installed

if [ "$button" = 1 ]; then
	while read line; do
		[[ $line == 'set $term'* ]] \
			&& i3 exec "${line##* } -e paru --noconfirm -Syu" &>/dev/null && break
	done <~/.config/i3/config
	declare -i count=0
elif [ "$button" = 3 ]; then
	update=$(checkupdates | awk '{print $1}' | rofi -dmenu -p 'update')
	if [ "$update" ]; then
		while read line; do
			[[ $line == 'set $term'* ]] \
				&& i3 exec "${line##* } -e paru --noconfirm -Syy $update && pkill -RTMIN+20 i3blocks" &>/dev/null && break
		done <~/.config/i3/config
	fi
fi
if [ -z $count ]; then
	[[ "$(uptime)" == *" 0 min, "* ]] && sleep 20
	declare -i count=0
	while read line; do
		[ "$line" ] && count+=1 \
			&& [[ $line == "linux"* ]] && URGENT=1
	done <<<$(checkupdates)
fi

TEXT=" <b>$count</b>"
printf '%s\n%s\n' "$TEXT" "$TEXT"
~/.config/i3blocks/colorcode $((100 + count))
[ "$URGENT" ] && exit 33 || exit 0
