#!/usr/bin/env bash
# Volume script
#Nice icons:       
if [ $button ]; then
  if [ $button -ge 4 ]; then
		pactl set-sink-volume 0	$([ $button -eq 4 ] && echo \+ || echo \-)10% &>/dev/null
	elif [ $button -eq 1 ]; then
		pactl set-sink-mute 0 toggle
	elif [ $button -eq 3 ]; then
		amixer set Capture toggle &>/dev/null
	elif [ $button -eq 2 ]; then
		i3 exec pavucontrol &>/dev/null
	fi
fi

INFO=()
while read -a LINE; do
	case "${LINE[0]}" in
		'volume:') INFO[0]=${LINE[4]//%};;
		'muted:') INFO[1]=${LINE[1]} && break;;
	esac
done <<< $(pacmd list-sinks)

if [ ${INFO[1]} = yes ]; then
	ICON=
elif [ ${INFO[0]} -ge 70 ]; then
	ICON=
elif [ ${INFO[0]} -ge 35 ]; then
	ICON=
else
	ICON=
fi

echo "$ICON<b> ${INFO[0]}%</b>"
echo "$ICON ${INFO[0]}%"
~/.config/i3blocks/colorcode ${INFO[0]}

