#!/bin/bash
#Volume detection script
#Nice icons:       
if [[ $button -ge 4 ]]; then
	pactl set-sink-volume @DEFAULT_SINK@ $([[ $button -eq 4 ]] && echo \+ || echo \-)10% >> /dev/null
elif [[ $button -eq 1 ]]; then
	pactl set-sink-mute @DEFAULT_SINK@ toggle
elif [[ $button -eq 3 ]]; then
	amixer set Capture toggle >> /dev/null
elif [[ $button -eq 2 ]]; then
	i3 exec pavucontrol >> /dev/null
fi

TEXT=$(pacmd list-sinks | awk '/front-left:/ { print $5 } /muted:/ { print $2; exit }' | sed "s/\%//")
NUM=$(echo $TEXT | awk '{ print $1 }')

if [[ $TEXT == *"yes"* ]]; then
	ICON=
elif [[ $NUM -ge 70 ]]; then
	ICON=
elif [[ $NUM -ge 35 ]]; then
	ICON=
else
	ICON=
fi

echo "$ICON<b> $NUM%</b>"
echo "$ICON $NUM%"
#echo "$COLOR"
~/.config/i3blocks/colorcode $NUM

