#!/bin/bash
# Copyright (C) 2020 Josef Litoš

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#Nice icons:       
if [[ $button -ge 4 ]]; then
	pactl set-sink-volume @DEFAULT_SINK@ $([[ $button -eq 4 ]] && echo \+ || echo \-)10% >> /dev/null
elif [[ $button -eq 1 ]]; then
	pactl set-sink-mute @DEFAULT_SINK@ toggle
elif [[ $button -eq 3 ]]; then
	amixer set Capture toggle >> /dev/null
fi

TEXT=$(pacmd list-sinks | awk '/front-left:/ { print $5 } /muted:/ { print $2; exit }' | sed "s/\%//")
NUM=$(echo $TEXT | awk '{ print $1 }')

if [[ $TEXT == *"yes"* ]]; then
	ICON=
elif [[ $NUM -ge 70 ]]; then
	ICON=
elif [[ $NUM -ge 35 ]]; then
	ICON=
else
	ICON=
fi

echo "$ICON<b> $NUM%</b>"
echo "$ICON $NUM%"
#echo "$COLOR"
~/.config/i3blocks/colorcode $NUM

