#!/bin/sh
#WiFi stat script

#Nice icons:    
if [[ $button -eq 1 ]]; then
	NAME="$(nmcli d wifi list | sed -n 's/^\*//;/:/p' | awk '{ print $8"\t"$2 }' | rofi -dmenu -location 3 -p  | awk '{ print $2 }')"
	if [ "$NAME" ]; then
		PASSWD="$(rofi -dmenu -location 3 -l 0 -passowrd -p )"
		if [ "$PASSWD" ]; then
			nmcli d wifi connect "$NAME" password "$PASSWD" >> /dev/null
		else
			nmcli d wifi connect "$NAME" >> /dev/null
		fi
	fi
fi
ON=$(ip a s wlp3s0 | grep "<.*UP.*>")
QUALITY=$(grep wlp /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
if [ $QUALITY ]; then
	SSID=$(nmcli | awk '{ print $4; exit }')
fi
TEXT=$([ "$ON" ] && ([ $QUALITY ] && echo " $QUALITY%: $SSID" || echo "" ) || echo "")

echo "$TEXT"
echo "$TEXT"
~/.config/i3blocks/colorcode $([[ -z $QUALITY && "$ON" ]] && echo 0 || echo $QUALITY)

