#!/usr/bin/env bash
# Internet status script

#Nice icons:    
if [[ $button -eq 1 ]]; then
	i3 exec -- st -e nmtui &>/dev/null
fi

if [ $BLOCK_INSTANCE ]; then
	read -a LINE <<< $(ip a s $BLOCK_INSTANCE)
else
	while read -a LINE; do
		[[ "${LINE[1]}" = wlp* ]] && break
	done <<< $(ip a)
	BLOCK_INSTANCE=wlp
fi
[[ "${LINE[2]}" = *UP* ]] && ON=1
if [ $ON ]; then
	while read -a LINE; do
		[[ "${LINE[0]}" = "$BLOCK_INSTANCE"* ]] &&\
			QUALITY=$[${LINE[2]%.*}*10/7] && break
	done < /proc/net/wireless
	[ $QUALITY ] && read -a LINE <<< $(nmcli) && SSID=${LINE[-1]}
fi
TEXT=$([ $ON ] && ([ $QUALITY ] && echo " $QUALITY%: $SSID" || echo "" ) || echo "")

echo "$TEXT"
echo "$TEXT"
~/.config/i3blocks/colorcode $([ -z "$QUALITY" -a "$ON" ] && echo 0 || echo $QUALITY)

